// vim:ft=asciidoc
= О сложности - попытка формализма
Ilya Kostarev
:stem: 

== Бритва Оккама

[quote, Альберт Эйнштейн, формулировка принципа «Бритвы Оккама»]
Всё следует упрощать до тех пор, пока это возможно, но не более того.

== Закон необходимого разнообразия

https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%BA%D0%BE%D0%BD_%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D0%BE%D0%B3%D0%BE_%D1%80%D0%B0%D0%B7%D0%BD%D0%BE%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%B8%D1%8F[wiki]

[asciimath]
++++
H(y) \geq H(x) - I(u,x) \\
где I(u,x) = H(u) - H(u|x) 
++++

[quote]
Простота хуже воровства 

== Метафора

Почти любую систему можно отразить графом. Например вершины это состояния и рёбра маркированы управляющими сигналами вызывающими переход состояния, в общем конечный автомат. Или вершинами принять узлы сложной системы и рёбрами связи между узлами. 
// А можно категорией 

== Работа управления

[asciimath]
++++
A(x,y,z) = H(y) * \log_z x = H(y) * \frac{log x}{log z} = \frac{H(y) * H(x)}{H(z)} 
++++

== Абстракции


=== Мастер теорема анализа алгоритмов

[asciimath]
++++
T(x) = a * T(\frac{n}{b}) + f(n)
++++

Единицей измерения работы управления предлагается принять Гюйгенс в честь отца основателя теории вероятностей.
